export const publication_data =
[
   {
      "title":" simultaneously resettable arguments of knowledge ",
      "microsoftpaperId":185553,
      "source":" [{u'U': u'https://link.springer.com/content/pdf/10.1007%2F978-3-642-28914-9_30.pdf', u'Ty': 3}, {u'U': u'https://link.springer.com/chapter/10.1007%2F978-3-642-28914-9_30', u'Ty': 1}, {u'U': u'http://dx.doi.org/10.1007/978-3-642-28914-9_30', u'Ty': 1}, {u'U': u'http://dblp.uni-trier.de/db/conf/tcc/tcc2012.html#ChoOSV12', u'Ty': 1}, {u'U': u'https://rd.springer.com/chapter/10.1007%2F978-3-642-28914-9_30', u'Ty': 1}, {u'U': u'http://www.iacr.org/archive/tcc2012/71940223/71940223.pdf', u'Ty': 1}, {u'U': u'http://link.springer.com/10.1007/978-3-642-28914-9_30', u'Ty': 0}] ",
      "authors":" [{u'AfN': u'university of california los angeles', u'AuN': u'chongwon cho'}, {u'AfN': u'university of california los angeles', u'AuN': u'rafail ostrovsky'}, {u'AfN': u'university of salerno', u'AuN': u'alessandra scafuro'}, {u'AfN': u'university of salerno', u'AuN': u'ivan visconti'}] ",
      "fieldsofStudy":" [{u'FN': u'commitment scheme'}, {u'FN': u'identification scheme'}, {u'FN': u'knowledge extraction'}, {u'FN': u'theoretical computer science'}, {u'FN': u'computer science'}] ",
      "abstractKeywords":" [u'arguments', u'knowledge', u'resettable', u'simultaneously'] ",
      "paperDisplay":" Simultaneously resettable arguments of knowledge ",
      "datePaper":" 2012-03-19 ",
      "journal":" ",
      "conference":" tcc ",
      "userID":43
   },
   {
      "title":"noise robust feature extraction for asr using the aurora 2 database ",
      "microsoftpaperId":193006,
      "source":" [{u'U': u'http://www.seas.ucla.edu/spapl/paper/zhu_eurospeech01.pdf', u'Ty': 3}, {u'U': u'https://www.researchgate.net/profile/Xiaodong_Cui/publication/221478032_Noise_robust_feature_extraction_for_ASR_using_the_Aurora_2_database/links/02e7e53a975323a75b000000.pdf', u'Ty': 3}, {u'U': u'http://www.ee.ucla.edu/~spapl/paper/zhu_eurospeech01.pdf', u'Ty': 1}, {u'U': u'http://dblp.uni-trier.de/db/conf/interspeech/interspeech2001.html#ZhuICA01', u'Ty': 1}] ",
      "authors":" [{u'AfN': u'university of california los angeles', u'AuN': u'qifeng zhu'}, {u'AfN': u'university of california los angeles', u'AuN': u'markus iseli'}, {u'AfN': u'university of california los angeles', u'AuN': u'xiaodong cui'}, {u'AfN': u'university of california los angeles', u'AuN': u'abeer alwan'}] ",
      "fieldsofStudy":" [{u'FN': u'variable frame rate'}, {u'FN': u'mel frequency cepstrum'}, {u'FN': u'harmonic'}, {u'FN': u'demodulation'}, {u'FN': u'front and back ends'}, {u'FN': u'word error rate'}, {u'FN': u'feature extraction'}, {u'FN': u'computational complexity theory'}, {u'FN': u'speech recognition'}, {u'FN': u'database'}, {u'FN': u'pattern recognition'}, {u'FN': u'artificial intelligence'}, {u'FN': u'computer science'}] ",
      "abstractKeywords":" [u'2', u'asr', u'aurora', u'database', u'extraction', u'feature', u'noise', u'robust'] ",
      "paperDisplay":" Noise Robust Feature Extraction for ASR using the Aurora 2 Database ",
      "datePaper":" 2001-01-01 ",
      "journal":" ",
      "conference":" interspeech ",
      "userID":78
   },
   {
      "title":"a prescription for perilous times reviewing geoffrey r stone perilous times free speech in war time from the sedition act of 1798 to the war on terrorism 2004 ",
      "microsoftpaperId":945338,
      "source":" [{u'U': u'http://scholarship.law.duke.edu/cgi/viewcontent.cgi?article=2038&context=faculty_scholarship', u'Ty': 3}, {u'U': u'https://scholarship.law.duke.edu/faculty_scholarship/1255/', u'Ty': 1}] ",
      "authors":" [{u'AuN': u'neil s siegel'}] ",
      "fieldsofStudy":" [{u'FN': u'sedition'}, {u'FN': u'spanish civil war'}, {u'FN': u'terrorism'}, {u'FN': u'national security'}, {u'FN': u'medical prescription'}, {u'FN': u'public administration'}, {u'FN': u'law'}, {u'FN': u'economics'}] ",
      "abstractKeywords":" [u'1798', u'2004', u'act', u'free', u'geoffrey', u'perilous', u'prescription', u'r', u'reviewing', u'sedition', u'speech', u'stone', u'terrorism', u'time', u'times', u'war'] ",
      "paperDisplay":" A Prescription for Perilous Times (Reviewing Geoffrey R. Stone, Perilous Times: Free Speech in War Time From the Sedition Act of 1798 to the War on Terrorism (2004)) ",
      "datePaper":" 2005-01-01 ",
      "journal":" ",
      "conference":" ",
      "userID":197
   },
   {
      "title":"a correlation maximization denoising filter used as an enhancement frontend for noise robust bird call classification ",
      "microsoftpaperId":998388,
      "source":" [{u'U': u'http://www.seas.ucla.edu/spapl/weichu/docs/chu_interspeech09_slides.pdf', u'Ty': 3}, {u'U': u'http://dblp.uni-trier.de/db/conf/interspeech/interspeech2009.html#ChuA09', u'Ty': 1}, {u'U': u'http://www.isca-speech.org/archive/interspeech_2009/i09_2831.html', u'Ty': 1}] ",
      "authors":" [{u'AfN': u'university of california los angeles', u'AuN': u'wei chu'}, {u'AfN': u'university of california los angeles', u'AuN': u'abeer alwan'}] ",
      "fieldsofStudy":" [{u'FN': u'wiener filter'}, {u'FN': u'maximization'}, {u'FN': u'mixture model'}, {u'FN': u'noise reduction'}, {u'FN': u'hidden markov model'}, {u'FN': u'word error rate'}, {u'FN': u'gaussian noise'}, {u'FN': u'feature extraction'}, {u'FN': u'speech recognition'}, {u'FN': u'pattern recognition'}, {u'FN': u'machine learning'}, {u'FN': u'artificial intelligence'}, {u'FN': u'computer science'}] ",
      "abstractKeywords":" [u'bird', u'call', u'classification', u'correlation', u'denoising', u'enhancement', u'filter', u'frontend', u'maximization', u'noise', u'robust'] ",
      "paperDisplay":" A correlation-maximization denoising filter used as an enhancement frontend for noise robust bird call classification. ",
      "datePaper":" 2009-01-01 ",
      "journal":" ",
      "conference":" interspeech ",
      "userID":78
   },
   {
      "title":"study of fully developed liquid metal open channel flow in a nearly coplanar magnetic field ",
      "microsoftpaperId":1188109,
      "source":" [{u'U': u'http://cat.inist.fr/?aModele=afficheN&cpsidt=2638555', u'Ty': 999}, {u'U': u'http://epubs.ans.org/?a=30816', u'Ty': 999}, {u'U': u'http://www.ans.org/pubs/journals/fst/a_30816', u'Ty': 999}, {u'U': u'http://www.osti.gov/scitech/biblio/466357', u'Ty': 999}, {u'U': u'https://www.tandfonline.com/doi/full/10.13182/FST97-A30816', u'Ty': 999}] ",
      "authors":" [{u'AuN': u'n b morley'}, {u'AfN': u'university of california los angeles', u'AuN': u'm a abdou'}] ",
      "fieldsofStudy":" [{u'FN': u'hartmann number'}, {u'FN': u'tokamak'}, {u'FN': u'open channel flow'}, {u'FN': u'magnetohydrodynamics'}, {u'FN': u'laminar flow'}, {u'FN': u'flow velocity'}, {u'FN': u'magnetic field'}, {u'FN': u'electrical resistivity and conductivity'}, {u'FN': u'classical mechanics'}, {u'FN': u'nuclear magnetic resonance'}, {u'FN': u'physics'}] ",
      "abstractKeywords":" [u'channel', u'coplanar', u'developed', u'field', u'flow', u'fully', u'liquid', u'magnetic', u'metal', u'nearly', u'open'] ",
      "paperDisplay":" Study of fully developed, liquid-metal, open-channel flow in a nearly coplanar magnetic field ",
      "datePaper":" 1997-01-03 ",
      "journal":" fusion technol ",
      "conference":" ",
      "userID":151
   },
   {
      "title":"an overview of digital communications techniques using chaos and nonlinear dynamics ",
      "microsoftpaperId":1550197,
      "source":" [{u'U': u'https://rd.springer.com/content/pdf/10.1007%2F0-387-29788-X_1.pdf', u'Ty': 3}, {u'U': u'https://link.springer.com/content/pdf/10.1007%2F0-387-29788-X_1.pdf', u'Ty': 3}, {u'U': u'https://link.springer.com/chapter/10.1007/0-387-29788-X_1', u'Ty': 1}, {u'U': u'https://rd.springer.com/chapter/10.1007/0-387-29788-X_1', u'Ty': 1}] ",
      "authors":" [{u'AfN': u'university of california', u'AuN': u'lawrence e larson'}, {u'AfN': u'university of california', u'AuN': u'lev s tsimring'}, {u'AfN': u'university of california', u'AuN': u'henry d i abarbanel'}, {u'AfN': u'university of california los angeles', u'AuN': u'jiaming liu'}, {u'AfN': u'university of california los angeles', u'AuN': u'kung yao'}, {u'AfN': u'university of california', u'AuN': u'alexander r volkovskii'}, {u'AfN': u'university of california', u'AuN': u'nikolai f rulkov'}, {u'AuN': u'mikhail m sushchik'}] ",
      "fieldsofStudy":" [{u'FN': u'optical communication'}, {u'FN': u'modulation'}, {u'FN': u'wireless'}, {u'FN': u'nonlinear system'}, {u'FN': u'control engineering'}, {u'FN': u'computer science'}] ",
      "abstractKeywords":" [u'chaos', u'communications', u'digital', u'dynamics', u'nonlinear', u'overview', u'techniques'] ",
      "paperDisplay":" An Overview of Digital Communications Techniques Using Chaos and Nonlinear Dynamics ",
      "datePaper":" 2006-01-01 ",
      "journal":" ",
      "conference":" ",
      "userID":113
   },
   {
      "title":"particle level set method ",
      "microsoftpaperId":1961060,
      "source":" [{u'U': u'https://link.springer.com/content/pdf/10.1007%2F0-387-22746-6_9.pdf', u'Ty': 3}, {u'U': u'https://link.springer.com/chapter/10.1007/0-387-22746-6_9', u'Ty': 1}] ",
      "authors":" [{u'AfN': u'university of california los angeles', u'AuN': u'stanley osher'}, {u'AfN': u'stanford university', u'AuN': u'ronald fedkiw'}] ",
      "fieldsofStudy":" [{u'FN': u'rarefaction'}, {u'FN': u'particle number'}, {u'FN': u'viscosity solution'}, {u'FN': u'level set method'}, {u'FN': u'level set'}, {u'FN': u'curvature'}, {u'FN': u'viscosity'}, {u'FN': u'vector field'}, {u'FN': u'mathematical analysis'}, {u'FN': u'mathematics'}] ",
      "abstractKeywords":" [u'level', u'particle', u'set'] ",
      "paperDisplay":" Particle Level Set Method ",
      "datePaper":" 2003-01-01 ",
      "journal":" ",
      "conference":" ",
      "userID":42
   },
   {
      "title":"3d depth cameras in vision benefits and limitations of the hardware ",
      "microsoftpaperId":2539321,
      "source":" [{u'U': u'https://link.springer.com/content/pdf/10.1007%2F978-3-319-08651-4_1.pdf', u'Ty': 3}, {u'U': u'https://rd.springer.com/content/pdf/10.1007%2F978-3-319-08651-4_1.pdf', u'Ty': 3}, {u'U': u'https://link.springer.com/chapter/10.1007%2F978-3-319-08651-4_1', u'Ty': 1}, {u'U': u'https://rd.springer.com/chapter/10.1007/978-3-319-08651-4_1', u'Ty': 1}, {u'U': u'http://link.springer.com/10.1007/978-3-319-08651-4_1', u'Ty': 0}] ",
      "authors":" [{u'AfN': u'massachusetts institute of technology', u'AuN': u'achuta kadambi'}, {u'AfN': u'massachusetts institute of technology', u'AuN': u'ayush bhandari'}, {u'AfN': u'massachusetts institute of technology', u'AuN': u'ramesh raskar'}] ",
      "fieldsofStudy":" [{u'FN': u'stereo cameras'}, {u'FN': u'bilateral filter'}, {u'FN': u'structured light'}, {u'FN': u'point cloud'}, {u'FN': u'computer vision'}, {u'FN': u'artificial intelligence'}, {u'FN': u'computer science'}] ",
      "abstractKeywords":" [u'3d', u'benefits', u'cameras', u'depth', u'hardware', u'limitations', u'vision'] ",
      "paperDisplay":" 3D Depth Cameras in Vision: Benefits and Limitations of the Hardware ",
      "datePaper":" 2014-01-01 ",
      "journal":" ",
      "conference":" ",
      "userID":107
   },
   {
      "title":"simulation of a 50gev pwfa stage ",
      "microsoftpaperId":2731502,
      "source":" [{u'U': u'http://adsabs.harvard.edu/abs/2004AIPC..737..433H', u'Ty': 1}, {u'U': u'http://aip.scitation.org/doi/abs/10.1063/1.1842574', u'Ty': 1}, {u'U': u'http://scitation.aip.org/content/aip/proceeding/aipcp/10.1063/1.1842574', u'Ty': 0}] ",
      "authors":" [{u'AfN': u'university of california los angeles', u'AuN': u'c huang'}, {u'AfN': u'university of california los angeles', u'AuN': u'w lu'}, {u'AfN': u'university of california los angeles', u'AuN': u'm zhou'}, {u'AfN': u'university of california los angeles', u'AuN': u'viktor k decyk'}, {u'AfN': u'university of california los angeles', u'AuN': u'w b mori'}, {u'AfN': u'university of southern california', u'AuN': u'e oz'}, {u'AfN': u'stanford university', u'AuN': u'c d barnes'}, {u'AfN': u'university of california los angeles', u'AuN': u'c e clayton'}, {u'AfN': u'university of california los angeles', u'AuN': u'f j decker'}, {u'AfN': u'university of southern california', u'AuN': u's deng'}, {u'AfN': u'stanford university', u'AuN': u'm j hogan'}, {u'AfN': u'stanford university', u'AuN': u'r iverson'}, {u'AfN': u'university of southern california', u'AuN': u'd k johnson'}, {u'AfN': u'university of california los angeles', u'AuN': u'c joshi'}, {u'AfN': u'university of southern california', u'AuN': u't katsouleas'}, {u'AfN': u'stanford university', u'AuN': u'p krejcik'}, {u'AfN': u'university of california los angeles', u'AuN': u'k a marsh'}, {u'AfN': u'university of southern california', u'AuN': u'p muggli'}, {u'AfN': u'stanford university', u'AuN': u'c o connell'}, {u'AfN': u'stanford university', u'AuN': u'd walz'}] ",
      "fieldsofStudy":" [{u'FN': u'waves in plasmas'}, {u'FN': u'particle beam'}, {u'FN': u'collider'}, {u'FN': u'phase velocity'}, {u'FN': u'beam'}, {u'FN': u'instability'}, {u'FN': u'electron'}, {u'FN': u'plasma'}, {u'FN': u'atomic physics'}, {u'FN': u'particle physics'}, {u'FN': u'physics'}] ",
      "abstractKeywords":" [u'50gev', u'pwfa', u'simulation', u'stage'] ",
      "paperDisplay":" Simulation of a 50GeV PWFA Stage ",
      "datePaper":" 2004-12-07 ",
      "journal":" ",
      "conference":" ",
      "userID":119
   },
   {
      "title":"abstract 2242 very high resolution near field imaging of ablation with a newly developed forward looking catheter mounted microlinear intracardiac imaging array ",
      "microsoftpaperId":2890717,
      "source":" [{u'U': u'http://circ.ahajournals.org/content/116/Suppl_16/II_488.3', u'Ty': 1}] ",
      "authors":" [{u'AfN': u'university of portland', u'AuN': u'david j sahn'}, {u'AfN': u'university of southern california', u'AuN': u'k kirk shung'}, {u'AfN': u'university of southern california', u'AuN': u'jonathan m cannata'}, {u'AfN': u'university of california davis', u'AuN': u'douglas n stephens'}, {u'AuN': u'raymond chia'}, {u'AuN': u'peter c y chen'}, {u'AuN': u'kai erik thomenius'}, {u'AuN': u'aaron dentinger'}, {u'AfN': u'university of portland', u'AuN': u'muhammad ashraf'}, {u'AfN': u'university of washington', u'AuN': u'matthew odonnell'}, {u'AfN': u'university of california los angeles', u'AuN': u'aman mahajan'}, {u'AfN': u'university of california los angeles', u'AuN': u'kalyanam shivkumar'}] ",
      "fieldsofStudy":" [{u'FN': u'strain rate imaging'}, {u'FN': u'intracardiac injection'}, {u'FN': u'ventricle'}, {u'FN': u'catheter'}, {u'FN': u'ablation'}, {u'FN': u'ultrasound'}, {u'FN': u'doppler effect'}, {u'FN': u'radio frequency'}, {u'FN': u'radiology'}, {u'FN': u'cardiology'}, {u'FN': u'internal medicine'}, {u'FN': u'medicine'}] ",
      "abstractKeywords":" [u'2242', u'ablation', u'array', u'catheter', u'developed', u'field', u'forward', u'high', u'imaging', u'intracardiac', u'looking', u'microlinear', u'mounted', u'newly', u'resolution'] ",
      "paperDisplay":" Abstract 2242: Very High Resolution Near Field Imaging of Ablation with a Newly-Developed Forward-Looking Catheter Mounted Microlinear Intracardiac Imaging Array ",
      "datePaper":" 2007-10-16 ",
      "journal":" circulation ",
      "conference":" ",
      "userID":31
   }
]