DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user(
   userID            INTEGER  NOT NULL PRIMARY KEY 
  ,email             VARCHAR(50) NOT NULL
  ,firstName         VARCHAR(50) NOT NULL
  ,lastName          VARCHAR(90) NOT NULL
  ,researchInterests text NOT NULL
  ,profilePicture    VARCHAR(255) NOT NULL
  ,ShibbolethLogin   VARCHAR(255) NOT NULL
);

INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (1,'aviz@cs.ucla.edu','Algirdas','Avizienis','computer system architecture and design, fault-tolerant computing, digital arithmetic','cs_faculty_images/profile_pic_Algirdas0.jpg','aviz@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (2,'rajive@cs.ucla.edu','Rajive','Bagrodia','wireless networks, mobile computing and communications, network simulation and analysis, parallel and distributed computing','cs_faculty_images/profile_pic_Rajive1.jpg','rajive@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (3,'cardenas@cs.ucla.edu','Alfonso','F. Cardenas','database management, distributed heterogeneous and multimedia systems, information systems, medical informatics, legal and IP issues, software engineering','cs_faculty_images/profile_pic_Alfonso2.jpg','cardenas@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (4,'jwc@cs.ucla.edu','Jack','Carlyle','communication, computation theory and practice, algorithms and complexity, discrete system theory, developmental and probabilistic systems','cs_faculty_images/profile_pic_Jack3.jpg','jwc@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (5,'kwchang@cs.ucla.edu','Kai-Wei','Chang','statistical approaches to natural language processing, tractable machine learning methods for complex and big data','cs_faculty_images/profile_pic_Kai-Wei4.jpg','kwchang@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (6,'cho@cs.ucla.edu','Junghoo','(John) Cho','internet search engines, database systems, information management systems, digital libraries, large-scale internet data management','cs_faculty_images/profile_pic_Junghoo5.jpg','cho@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (7,'wwc@cs.ucla.edu','Wesley','Chu','distributed processing and distributed database systems, intelligent information systems','cs_faculty_images/profile_pic_Wesley6.jpg','wwc@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (8,'tcondie@cs.ucla.edu','Tyson','Condie','provide appropriate data management toolkits for the data scientist','cs_faculty_images/profile_pic_Tyson7.jpg','tcondie@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (9,'cong@cs.ucla.edu','Jason','(Jingsheng) Cong','computer-aided design of VLSI circuits, fault-tolerant designs of VLSI systems, design and analysis of algorithms','cs_faculty_images/profile_pic_Jason8.jpg','cong@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (10,'darwiche@cs.ucla.edu','Adnan','Darwiche','probabilistic and logical reasoning and its applications, including diagnosis, planning, and system design and analysis','cs_faculty_images/profile_pic_Adnan9.jpg','darwiche@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (11,'joed@cs.ucla.edu','Joseph','DiStefano III','biocybernetics, computational systems biology and physiology, biomedical systems modeling and control, integrative cancer biology, optimal drug therapy, intelligent software for automated biomodeling','cs_faculty_images/profile_pic_Joseph10.jpg','joed@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (12,'dyer@cs.ucla.edu','Michael','G. Dyer','processing and acquisition of natural language through symbolic, connectionist and genetic algorithm techniques','cs_faculty_images/profile_pic_Michael11.jpg','dyer@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (13,'eggert@cs.ucla.edu','Paul','Eggert','software design and engineering, programming language design and implementation, software internationalization','cs_faculty_images/profile_pic_Paul12.jpg','eggert@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (14,'jason.ernst@ucla.edu','Jason','Ernst','computational biology, bioinformatics, machine learning','cs_faculty_images/profile_pic_Jason13.jpg','jason.ernst@ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (15,'milos@cs.ucla.edu','Milos','D. Ercegovac','computer arithmetic and hardware-oriented algorithms, design of digital and reconfigurable systems','cs_faculty_images/profile_pic_Milos14.jpg','milos@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (16,'eeskin@cs.ucla.edu','Eleazar','Eskin','bioinformatics, computational biology, machine learning','cs_faculty_images/profile_pic_Eleazar15.jpg','eeskin@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (17,'destrin@cs.ucla.edu','Deborah','Estrin','embedded networked sensing, wireless sensing applications, environmental monitoring, network protocols','cs_faculty_images/profile_pic_Deborah16.jpg','destrin@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (18,'akflectcher@ucla.edu','Alyson','Fletcher','applied mathematics including inverse problems, statistical physics','cs_faculty_images/profile_pic_Alyson17.jpg','akflectcher@ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (19,'eli@cs.ucla.edu','Eliezer','Gafni','distributed algorithms, mathematical programing with application to data networks, computer science theory','cs_faculty_images/profile_pic_Eliezer18.jpg','eli@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (20,'gerla@cs.ucla.edu','Mario','Gerla','wireless ad hoc networks, peer to peer communications, dynamic spectrum access, wireless security, mobile health system','cs_faculty_images/profile_pic_Mario19.jpg','gerla@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (21,'greibach@cs.ucla.edu','Sheila','Greibach','algorithms and computational complexity, program schemes and semantics, formal languages and automata theory and computability','cs_faculty_images/profile_pic_Sheila20.jpg','greibach@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (22,'qgu@cs.ucla.edu','Quanquan','Gu','machine learning, data mining and optimization algorithms, computational genomics','cs_faculty_images/profile_pic_Quanquan21.jpg','qgu@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (23,'ehalperin@cs.ucla.edu','Eran','Halperin','computational biology, machine learning, algorithms, population genetics, statistical genetics','cs_faculty_images/profile_pic_Eran22.jpg','ehalperin@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (24,'heckerma@hotmail.com','David','Heckerman','learning from data, graphical models, data analysis and visualization in biology and medicine, design of HIV vaccines, genome-wide association studies','cs_faculty_images/profile_pic_David23.jpg','heckerma@hotmail.com');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (25,'chojui.hsieh@gmail.com','Cho-Jui','Hsieh','machine learning, data mining, optimization, adversarial deep learning','cs_faculty_images/profile_pic_Cho-Jui24.jpg','chojui.hsieh@gmail.com');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (26,'vanj@google.com','Van','Jacobson','internet architecture, named data network (NDN)','cs_faculty_images/profile_pic_Van25.jpg','vanj@google.com');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (27,'alan.kay@squeakland.org','Alan','Kay','object-oriented programming, personal computing, graphical user interfaces','cs_faculty_images/profile_pic_Alan26.jpg','alan.kay@squeakland.org');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (28,'miryung@cs.ucla.edu','Miryung','Kim','software engineering, debugging and analytics for big data systems, data scientists in software engineering','cs_faculty_images/profile_pic_Miryung27.jpg','miryung@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (29,'lk@cs.ucla.edu','Leonard','Kleinrock','queueing theory, packet switching networks, packet radio networks, local area networks, broadband networks, nomadic computing, peer-to-peer networks, intelligent agents','cs_faculty_images/profile_pic_Leonard28.jpg','lk@cs.ucla.edu');
INSERT INTO user(userID,email,firstName,lastName,researchInterests,profilePicture,ShibbolethLogin) VALUES (30,'klinger@cs.ucla.edu','Allen','Klinger','image analysis, pattern analysis, database systems, computer education','cs_faculty_images/profile_pic_Allen29.jpg','klinger@cs.ucla.edu');







DROP TABLE IF EXISTS publications;
CREATE TABLE IF NOT EXISTS publications(
   title            text NOT NULL 
  ,microsoftpaperId BIGINT  NOT NULL PRIMARY KEY
  ,source           text NOT NULL
  ,authors          text NOT NULL
  ,fieldsofStudy    text NOT NULL
  ,abstractKeywords text NOT NULL
  ,paperDisplay     text NOT NULL
  ,datePaper        DATE  NOT NULL
  ,journal          VARCHAR(255)
  ,conference       VARCHAR(255)
  ,userID           INTEGER  NOT NULL
);


INSERT INTO publications(title,microsoftpaperId,source,authors,fieldsofStudy,abstractKeywords,paperDisplay,datePaper,journal,conference,userID) VALUES ('simultaneously resettable arguments of knowledge',185553,'[{u''U'': u''https://link.springer.com/content/pdf/10.1007%2F978-3-642-28914-9_30.pdf'', u''Ty'': 3}, {u''U'': u''https://link.springer.com/chapter/10.1007%2F978-3-642-28914-9_30'', u''Ty'': 1}, {u''U'': u''http://dx.doi.org/10.1007/978-3-642-28914-9_30'', u''Ty'': 1}, {u''U'': u''http://dblp.uni-trier.de/db/conf/tcc/tcc2012.html#ChoOSV12'', u''Ty'': 1}, {u''U'': u''https://rd.springer.com/chapter/10.1007%2F978-3-642-28914-9_30'', u''Ty'': 1}, {u''U'': u''http://www.iacr.org/archive/tcc2012/71940223/71940223.pdf'', u''Ty'': 1}, {u''U'': u''http://link.springer.com/10.1007/978-3-642-28914-9_30'', u''Ty'': 0}]','[{u''AfN'': u''university of california los angeles'', u''AuN'': u''chongwon cho''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''rafail ostrovsky''}, {u''AfN'': u''university of salerno'', u''AuN'': u''alessandra scafuro''}, {u''AfN'': u''university of salerno'', u''AuN'': u''ivan visconti''}]','[{u''FN'': u''commitment scheme''}, {u''FN'': u''identification scheme''}, {u''FN'': u''knowledge extraction''}, {u''FN'': u''theoretical computer science''}, {u''FN'': u''computer science''}]','[u''arguments'', u''knowledge'', u''resettable'', u''simultaneously'']','Simultaneously resettable arguments of knowledge','2012-03-19',NULL,'tcc',43);
INSERT INTO publications(title,microsoftpaperId,source,authors,fieldsofStudy,abstractKeywords,paperDisplay,datePaper,journal,conference,userID) VALUES ('noise robust feature extraction for asr using the aurora 2 database',193006,'[{u''U'': u''http://www.seas.ucla.edu/spapl/paper/zhu_eurospeech01.pdf'', u''Ty'': 3}, {u''U'': u''https://www.researchgate.net/profile/Xiaodong_Cui/publication/221478032_Noise_robust_feature_extraction_for_ASR_using_the_Aurora_2_database/links/02e7e53a975323a75b000000.pdf'', u''Ty'': 3}, {u''U'': u''http://www.ee.ucla.edu/~spapl/paper/zhu_eurospeech01.pdf'', u''Ty'': 1}, {u''U'': u''http://dblp.uni-trier.de/db/conf/interspeech/interspeech2001.html#ZhuICA01'', u''Ty'': 1}]','[{u''AfN'': u''university of california los angeles'', u''AuN'': u''qifeng zhu''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''markus iseli''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''xiaodong cui''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''abeer alwan''}]','[{u''FN'': u''variable frame rate''}, {u''FN'': u''mel frequency cepstrum''}, {u''FN'': u''harmonic''}, {u''FN'': u''demodulation''}, {u''FN'': u''front and back ends''}, {u''FN'': u''word error rate''}, {u''FN'': u''feature extraction''}, {u''FN'': u''computational complexity theory''}, {u''FN'': u''speech recognition''}, {u''FN'': u''database''}, {u''FN'': u''pattern recognition''}, {u''FN'': u''artificial intelligence''}, {u''FN'': u''computer science''}]','[u''2'', u''asr'', u''aurora'', u''database'', u''extraction'', u''feature'', u''noise'', u''robust'']','Noise Robust Feature Extraction for ASR using the Aurora 2 Database','2001-01-01',NULL,'interspeech',78);
INSERT INTO publications(title,microsoftpaperId,source,authors,fieldsofStudy,abstractKeywords,paperDisplay,datePaper,journal,conference,userID) VALUES ('a prescription for perilous times reviewing geoffrey r stone perilous times free speech in war time from the sedition act of 1798 to the war on terrorism 2004',945338,'[{u''U'': u''http://scholarship.law.duke.edu/cgi/viewcontent.cgi?article=2038&context=faculty_scholarship'', u''Ty'': 3}, {u''U'': u''https://scholarship.law.duke.edu/faculty_scholarship/1255/'', u''Ty'': 1}]','[{u''AuN'': u''neil s siegel''}]','[{u''FN'': u''sedition''}, {u''FN'': u''spanish civil war''}, {u''FN'': u''terrorism''}, {u''FN'': u''national security''}, {u''FN'': u''medical prescription''}, {u''FN'': u''public administration''}, {u''FN'': u''law''}, {u''FN'': u''economics''}]','[u''1798'', u''2004'', u''act'', u''free'', u''geoffrey'', u''perilous'', u''prescription'', u''r'', u''reviewing'', u''sedition'', u''speech'', u''stone'', u''terrorism'', u''time'', u''times'', u''war'']','A Prescription for Perilous Times (Reviewing Geoffrey R. Stone, Perilous Times: Free Speech in War Time From the Sedition Act of 1798 to the War on Terrorism (2004))','2005-01-01',NULL,NULL,197);
INSERT INTO publications(title,microsoftpaperId,source,authors,fieldsofStudy,abstractKeywords,paperDisplay,datePaper,journal,conference,userID) VALUES ('a correlation maximization denoising filter used as an enhancement frontend for noise robust bird call classification',998388,'[{u''U'': u''http://www.seas.ucla.edu/spapl/weichu/docs/chu_interspeech09_slides.pdf'', u''Ty'': 3}, {u''U'': u''http://dblp.uni-trier.de/db/conf/interspeech/interspeech2009.html#ChuA09'', u''Ty'': 1}, {u''U'': u''http://www.isca-speech.org/archive/interspeech_2009/i09_2831.html'', u''Ty'': 1}]','[{u''AfN'': u''university of california los angeles'', u''AuN'': u''wei chu''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''abeer alwan''}]','[{u''FN'': u''wiener filter''}, {u''FN'': u''maximization''}, {u''FN'': u''mixture model''}, {u''FN'': u''noise reduction''}, {u''FN'': u''hidden markov model''}, {u''FN'': u''word error rate''}, {u''FN'': u''gaussian noise''}, {u''FN'': u''feature extraction''}, {u''FN'': u''speech recognition''}, {u''FN'': u''pattern recognition''}, {u''FN'': u''machine learning''}, {u''FN'': u''artificial intelligence''}, {u''FN'': u''computer science''}]','[u''bird'', u''call'', u''classification'', u''correlation'', u''denoising'', u''enhancement'', u''filter'', u''frontend'', u''maximization'', u''noise'', u''robust'']','A correlation-maximization denoising filter used as an enhancement frontend for noise robust bird call classification.','2009-01-01',NULL,'interspeech',78);
INSERT INTO publications(title,microsoftpaperId,source,authors,fieldsofStudy,abstractKeywords,paperDisplay,datePaper,journal,conference,userID) VALUES ('study of fully developed liquid metal open channel flow in a nearly coplanar magnetic field',1188109,'[{u''U'': u''http://cat.inist.fr/?aModele=afficheN&cpsidt=2638555'', u''Ty'': 999}, {u''U'': u''http://epubs.ans.org/?a=30816'', u''Ty'': 999}, {u''U'': u''http://www.ans.org/pubs/journals/fst/a_30816'', u''Ty'': 999}, {u''U'': u''http://www.osti.gov/scitech/biblio/466357'', u''Ty'': 999}, {u''U'': u''https://www.tandfonline.com/doi/full/10.13182/FST97-A30816'', u''Ty'': 999}]','[{u''AuN'': u''n b morley''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''m a abdou''}]','[{u''FN'': u''hartmann number''}, {u''FN'': u''tokamak''}, {u''FN'': u''open channel flow''}, {u''FN'': u''magnetohydrodynamics''}, {u''FN'': u''laminar flow''}, {u''FN'': u''flow velocity''}, {u''FN'': u''magnetic field''}, {u''FN'': u''electrical resistivity and conductivity''}, {u''FN'': u''classical mechanics''}, {u''FN'': u''nuclear magnetic resonance''}, {u''FN'': u''physics''}]','[u''channel'', u''coplanar'', u''developed'', u''field'', u''flow'', u''fully'', u''liquid'', u''magnetic'', u''metal'', u''nearly'', u''open'']','Study of fully developed, liquid-metal, open-channel flow in a nearly coplanar magnetic field','1997-01-03','fusion technol',NULL,151);
INSERT INTO publications(title,microsoftpaperId,source,authors,fieldsofStudy,abstractKeywords,paperDisplay,datePaper,journal,conference,userID) VALUES ('an overview of digital communications techniques using chaos and nonlinear dynamics',1550197,'[{u''U'': u''https://rd.springer.com/content/pdf/10.1007%2F0-387-29788-X_1.pdf'', u''Ty'': 3}, {u''U'': u''https://link.springer.com/content/pdf/10.1007%2F0-387-29788-X_1.pdf'', u''Ty'': 3}, {u''U'': u''https://link.springer.com/chapter/10.1007/0-387-29788-X_1'', u''Ty'': 1}, {u''U'': u''https://rd.springer.com/chapter/10.1007/0-387-29788-X_1'', u''Ty'': 1}]','[{u''AfN'': u''university of california'', u''AuN'': u''lawrence e larson''}, {u''AfN'': u''university of california'', u''AuN'': u''lev s tsimring''}, {u''AfN'': u''university of california'', u''AuN'': u''henry d i abarbanel''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''jiaming liu''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''kung yao''}, {u''AfN'': u''university of california'', u''AuN'': u''alexander r volkovskii''}, {u''AfN'': u''university of california'', u''AuN'': u''nikolai f rulkov''}, {u''AuN'': u''mikhail m sushchik''}]','[{u''FN'': u''optical communication''}, {u''FN'': u''modulation''}, {u''FN'': u''wireless''}, {u''FN'': u''nonlinear system''}, {u''FN'': u''control engineering''}, {u''FN'': u''computer science''}]','[u''chaos'', u''communications'', u''digital'', u''dynamics'', u''nonlinear'', u''overview'', u''techniques'']','An Overview of Digital Communications Techniques Using Chaos and Nonlinear Dynamics','2006-01-01',NULL,NULL,113);
INSERT INTO publications(title,microsoftpaperId,source,authors,fieldsofStudy,abstractKeywords,paperDisplay,datePaper,journal,conference,userID) VALUES ('particle level set method',1961060,'[{u''U'': u''https://link.springer.com/content/pdf/10.1007%2F0-387-22746-6_9.pdf'', u''Ty'': 3}, {u''U'': u''https://link.springer.com/chapter/10.1007/0-387-22746-6_9'', u''Ty'': 1}]','[{u''AfN'': u''university of california los angeles'', u''AuN'': u''stanley osher''}, {u''AfN'': u''stanford university'', u''AuN'': u''ronald fedkiw''}]','[{u''FN'': u''rarefaction''}, {u''FN'': u''particle number''}, {u''FN'': u''viscosity solution''}, {u''FN'': u''level set method''}, {u''FN'': u''level set''}, {u''FN'': u''curvature''}, {u''FN'': u''viscosity''}, {u''FN'': u''vector field''}, {u''FN'': u''mathematical analysis''}, {u''FN'': u''mathematics''}]','[u''level'', u''particle'', u''set'']','Particle Level Set Method','2003-01-01',NULL,NULL,42);
INSERT INTO publications(title,microsoftpaperId,source,authors,fieldsofStudy,abstractKeywords,paperDisplay,datePaper,journal,conference,userID) VALUES ('3d depth cameras in vision benefits and limitations of the hardware',2539321,'[{u''U'': u''https://link.springer.com/content/pdf/10.1007%2F978-3-319-08651-4_1.pdf'', u''Ty'': 3}, {u''U'': u''https://rd.springer.com/content/pdf/10.1007%2F978-3-319-08651-4_1.pdf'', u''Ty'': 3}, {u''U'': u''https://link.springer.com/chapter/10.1007%2F978-3-319-08651-4_1'', u''Ty'': 1}, {u''U'': u''https://rd.springer.com/chapter/10.1007/978-3-319-08651-4_1'', u''Ty'': 1}, {u''U'': u''http://link.springer.com/10.1007/978-3-319-08651-4_1'', u''Ty'': 0}]','[{u''AfN'': u''massachusetts institute of technology'', u''AuN'': u''achuta kadambi''}, {u''AfN'': u''massachusetts institute of technology'', u''AuN'': u''ayush bhandari''}, {u''AfN'': u''massachusetts institute of technology'', u''AuN'': u''ramesh raskar''}]','[{u''FN'': u''stereo cameras''}, {u''FN'': u''bilateral filter''}, {u''FN'': u''structured light''}, {u''FN'': u''point cloud''}, {u''FN'': u''computer vision''}, {u''FN'': u''artificial intelligence''}, {u''FN'': u''computer science''}]','[u''3d'', u''benefits'', u''cameras'', u''depth'', u''hardware'', u''limitations'', u''vision'']','3D Depth Cameras in Vision: Benefits and Limitations of the Hardware','2014-01-01',NULL,NULL,107);
INSERT INTO publications(title,microsoftpaperId,source,authors,fieldsofStudy,abstractKeywords,paperDisplay,datePaper,journal,conference,userID) VALUES ('simulation of a 50gev pwfa stage',2731502,'[{u''U'': u''http://adsabs.harvard.edu/abs/2004AIPC..737..433H'', u''Ty'': 1}, {u''U'': u''http://aip.scitation.org/doi/abs/10.1063/1.1842574'', u''Ty'': 1}, {u''U'': u''http://scitation.aip.org/content/aip/proceeding/aipcp/10.1063/1.1842574'', u''Ty'': 0}]','[{u''AfN'': u''university of california los angeles'', u''AuN'': u''c huang''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''w lu''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''m zhou''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''viktor k decyk''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''w b mori''}, {u''AfN'': u''university of southern california'', u''AuN'': u''e oz''}, {u''AfN'': u''stanford university'', u''AuN'': u''c d barnes''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''c e clayton''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''f j decker''}, {u''AfN'': u''university of southern california'', u''AuN'': u''s deng''}, {u''AfN'': u''stanford university'', u''AuN'': u''m j hogan''}, {u''AfN'': u''stanford university'', u''AuN'': u''r iverson''}, {u''AfN'': u''university of southern california'', u''AuN'': u''d k johnson''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''c joshi''}, {u''AfN'': u''university of southern california'', u''AuN'': u''t katsouleas''}, {u''AfN'': u''stanford university'', u''AuN'': u''p krejcik''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''k a marsh''}, {u''AfN'': u''university of southern california'', u''AuN'': u''p muggli''}, {u''AfN'': u''stanford university'', u''AuN'': u''c o connell''}, {u''AfN'': u''stanford university'', u''AuN'': u''d walz''}]','[{u''FN'': u''waves in plasmas''}, {u''FN'': u''particle beam''}, {u''FN'': u''collider''}, {u''FN'': u''phase velocity''}, {u''FN'': u''beam''}, {u''FN'': u''instability''}, {u''FN'': u''electron''}, {u''FN'': u''plasma''}, {u''FN'': u''atomic physics''}, {u''FN'': u''particle physics''}, {u''FN'': u''physics''}]','[u''50gev'', u''pwfa'', u''simulation'', u''stage'']','Simulation of a 50GeV PWFA Stage','2004-12-07',NULL,NULL,119);
INSERT INTO publications(title,microsoftpaperId,source,authors,fieldsofStudy,abstractKeywords,paperDisplay,datePaper,journal,conference,userID) VALUES ('abstract 2242 very high resolution near field imaging of ablation with a newly developed forward looking catheter mounted microlinear intracardiac imaging array',2890717,'[{u''U'': u''http://circ.ahajournals.org/content/116/Suppl_16/II_488.3'', u''Ty'': 1}]','[{u''AfN'': u''university of portland'', u''AuN'': u''david j sahn''}, {u''AfN'': u''university of southern california'', u''AuN'': u''k kirk shung''}, {u''AfN'': u''university of southern california'', u''AuN'': u''jonathan m cannata''}, {u''AfN'': u''university of california davis'', u''AuN'': u''douglas n stephens''}, {u''AuN'': u''raymond chia''}, {u''AuN'': u''peter c y chen''}, {u''AuN'': u''kai erik thomenius''}, {u''AuN'': u''aaron dentinger''}, {u''AfN'': u''university of portland'', u''AuN'': u''muhammad ashraf''}, {u''AfN'': u''university of washington'', u''AuN'': u''matthew odonnell''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''aman mahajan''}, {u''AfN'': u''university of california los angeles'', u''AuN'': u''kalyanam shivkumar''}]','[{u''FN'': u''strain rate imaging''}, {u''FN'': u''intracardiac injection''}, {u''FN'': u''ventricle''}, {u''FN'': u''catheter''}, {u''FN'': u''ablation''}, {u''FN'': u''ultrasound''}, {u''FN'': u''doppler effect''}, {u''FN'': u''radio frequency''}, {u''FN'': u''radiology''}, {u''FN'': u''cardiology''}, {u''FN'': u''internal medicine''}, {u''FN'': u''medicine''}]','[u''2242'', u''ablation'', u''array'', u''catheter'', u''developed'', u''field'', u''forward'', u''high'', u''imaging'', u''intracardiac'', u''looking'', u''microlinear'', u''mounted'', u''newly'', u''resolution'']','Abstract 2242: Very High Resolution Near Field Imaging of Ablation with a Newly-Developed Forward-Looking Catheter Mounted Microlinear Intracardiac Imaging Array','2007-10-16','circulation',NULL,31);


