var express = require('express');
var router = express.Router();
var sql = require('./../db.js');


/* GET users listing. */
router.get('/', function(req, res, next) {
        res.send(
            {
                "UNIQUE_ID": "XWH4uCOHe6hAeAhKakzAeQAAAAE",
                "HTTPS": "on",
                "SSL_TLS_SNI": "ushare.idre.ucla.edu",
                "SSL_SERVER_S_DN_C": "US",
                "SSL_SERVER_S_DN_ST": "CA",
                "SSL_SERVER_S_DN_L": "Los Angeles",
                "SSL_SERVER_S_DN_O": "University of California, Los Angeles",
                "SSL_SERVER_S_DN_OU": "Office of Information Technology",
                "SSL_SERVER_S_DN_CN": "ushare.idre.ucla.edu",
                "SSL_SERVER_I_DN_C": "US",
                "SSL_SERVER_I_DN_ST": "MI",
                "SSL_SERVER_I_DN_L": "Ann Arbor",
                "SSL_SERVER_I_DN_O": "Internet2",
                "SSL_SERVER_I_DN_OU": "InCommon",
                "SSL_SERVER_I_DN_CN": "InCommon RSA Server CA",
                "SSL_SERVER_SAN_DNS_0": "ushare.idre.ucla.edu",
                "SSL_VERSION_INTERFACE": "mod_ssl\/2.4.6",
                "SSL_VERSION_LIBRARY": "OpenSSL\/1.0.1e-fips",
                "SSL_PROTOCOL": "TLSv1.2",
                "SSL_SECURE_RENEG": "true",
                "SSL_COMPRESS_METHOD": "NULL",
                "SSL_CIPHER": "ECDHE-RSA-AES128-GCM-SHA256",
                "SSL_CIPHER_EXPORT": "false",
                "SSL_CIPHER_USEKEYSIZE": "128",
                "SSL_CIPHER_ALGKEYSIZE": "128",
                "SSL_CLIENT_VERIFY": "NONE",
                "SSL_SERVER_M_VERSION": "3",
                "SSL_SERVER_M_SERIAL": "6A67BD8AFE257CAF27F0149532EF8DBB",
                "SSL_SERVER_V_START": "Oct 20 00:00:00 2017 GMT",
                "SSL_SERVER_V_END": "Oct 19 23:59:59 2020 GMT",
                "SSL_SERVER_S_DN": "CN=ushare.idre.ucla.edu,OU=Office of Information Technology,O=University of California\\, Los Angeles,street=405 Hilgard Avenue,L=Los Angeles,ST=CA,postalCode=90095,C=US",
                "SSL_SERVER_I_DN": "CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US",
                "SSL_SERVER_A_KEY": "rsaEncryption",
                "SSL_SERVER_A_SIG": "sha256WithRSAEncryption",
                "SSL_SESSION_ID": "1af4b6a0073a53957c4a59bcb44adc8f4a0db8786e98dd1d4a624ad0e23f91c4",
                "SSL_SESSION_RESUMED": "Resumed",
                "Shib-Handler": "https:\/\/ushare.idre.ucla.edu\/Shibboleth.sso",
                "Shib-Application-ID": "default",
                "Shib-Session-ID": "_0fc500591969f2b5ea2aee0d6101f1d9",
                "Shib-Identity-Provider": "urn:mace:incommon:ucla.edu",
                "Shib-Authentication-Instant": "2019-08-25T02:56:51.209Z",
                "Shib-Authentication-Method": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
                "Shib-AuthnContext-Class": "urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport",
                "Shib-Session-Index": "_7cfd94c9ccafdeebb6e7d7321247e963",
                "SHIBDISPLAYNAME": "SAHAI, UDAYAN",
                "SHIBEDUPERSONAFFILIATION": "student;member",
                "SHIBEDUPERSONPRINCIPALNAME": "udasahai@ucla.edu",
                "SHIBEDUPERSONTARGETEDID": "WkviU3PynOqrRX5JxGjnwaeVZdA=",
                "SHIBGIVENNAME": "UDAYAN",
                "SHIBMAIL": "udasahai@gmail.com",
                "HTTP_HOST": "ushare.idre.ucla.edu",
                "HTTP_CONNECTION": "keep-alive",
                "HTTP_UPGRADE_INSECURE_REQUESTS": "1",
                "HTTP_USER_AGENT": "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/76.0.3809.100 Safari\/537.36",
                "HTTP_SEC_FETCH_MODE": "navigate",
                "HTTP_SEC_FETCH_USER": "?1",
                "HTTP_ACCEPT": "text\/html,application\/xhtml+xml,application\/xml;q=0.9,image\/webp,image\/apng,*\/*;q=0.8,application\/signed-exchange;v=b3",
                "HTTP_SEC_FETCH_SITE": "none",
                "HTTP_ACCEPT_ENCODING": "gzip, deflate, br",
                "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.9,hi;q=0.8",
                "HTTP_COOKIE": "wordpress_logged_in_ba0962ed57762ac11be1b0773cff1b43=udasahai%40ucla.edu%7C1566874539%7Cze9PWQgvI3JhasQeNwHmS4WsnbBytnk6fq6eumCX0e7%7C4af47b3313327f59eb8e8ff207baa407a915561efc807a75ee1edbbe2a46e3a9; _ga=GA1.2.350217513.1556105692; iwe_user_noticecount_urn%3amace%3aucla.edu%3appid%3aperson%3a12D2FBD4BA81480895CC633D636727A0=0; ISIS%5Fticket=ticket=; iwe_term_student=191; iwe_session_cd_student=%25; __cfduid=dcade58bb18b2656ff0937f9c1ecf15b51561495694; iwe_term_student_urn%3amace%3aucla.edu%3appid%3aperson%3a12D2FBD4BA81480895CC633D636727A0=191; iwe_term_enrollment_urn%3amace%3aucla.edu%3appid%3aperson%3a12D2FBD4BA81480895CC633D636727A0=191; _shibsession_64656661756c7468747470733a2f2f7573686172652e696472652e75636c612e6564752f73686962626f6c6574682d7370=_0fc500591969f2b5ea2aee0d6101f1d9",
                "PATH": "\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin",
                "SERVER_SIGNATURE": "",
                "SERVER_SOFTWARE": "Apache\/2.4.6 (CentOS) OpenSSL\/1.0.1e-fips PHP\/7.2.2RC1",
                "SERVER_NAME": "ushare.idre.ucla.edu",
                "SERVER_ADDR": "128.97.60.182",
                "SERVER_PORT": "443",
                "REMOTE_ADDR": "173.197.219.141",
                "DOCUMENT_ROOT": "\/var\/www\/html-ssl",
                "REQUEST_SCHEME": "https",
                "CONTEXT_PREFIX": "",
                "CONTEXT_DOCUMENT_ROOT": "\/var\/www\/html-ssl",
                "SERVER_ADMIN": "root@localhost",
                "SCRIPT_FILENAME": "\/var\/www\/html-ssl\/ushare\/shib_json.php",
                "REMOTE_PORT": "60412",
                "REMOTE_USER": "",
                "AUTH_TYPE": "shibboleth",
                "GATEWAY_INTERFACE": "CGI\/1.1",
                "SERVER_PROTOCOL": "HTTP\/1.1",
                "REQUEST_METHOD": "GET",
                "QUERY_STRING": "",
                "REQUEST_URI": "\/ushare\/shib_json.php",
                "SCRIPT_NAME": "\/ushare\/shib_json.php",
                "PHP_SELF": "\/ushare\/shib_json.php",
                "PHP_AUTH_USER": "",
                "REQUEST_TIME_FLOAT": 1566701752.928,
                "REQUEST_TIME": 1566701752
              }
        );
	});

module.exports = router;